version: '3.8'

services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    image: url-shortener:latest
    container_name: url-shortener
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=url-shortener
      - LOGGING_LEVEL_ORG_URL_SHORTENER=INFO
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/urls"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped

